### PR TITLE
docs: reference problem to goal when contributing

### PR DESCRIPTION
**Pull request by Fils7**
### ETA
10 minutes

Resolves [#1](https://github.com/clearpool-finance/developers/issues/1)

### CODE REVIEW

**Comment by georgeciubotaru** [comment]
@Fils7 Wrong title, in your case you are adding `docs`

**Comment by Fils7** [comment]
Can't assign any one for review and can't submit PR cost.

FYI @georgeciubotaru , @zolotokrylin

**Review by zolotokrylin — CHANGES_REQUESTED** [review]
@Fils7 use [this link](https://github.com/clearpool-finance/developers/compare/main...chore/reference-from-Problem-to-Goal) to create a pull request.

1. You will be able to submit the time
2. You will be able to assign people for a review

**Comment by zolotokrylin** [comment]
Moved to here: https://github.com/clearpool-finance/developers/pull/2

**Pull request closed without merging**
